// apps/keycloak-theme/src/login/components/MatrixRain.tsx
import { useEffect, useRef } from "react";
import { createMatrixRain } from "matrix-rain";

export default function MatrixRain() {
    const canvasRef = useRef<HTMLCanvasElement>(null);

    useEffect(() => {
        const instance = createMatrixRain(canvasRef.current!, { color: [255, 94, 31], headColor: [255, 240, 220] });
        return () => instance.destroy();
    }, []);

    return (
        <canvas
            ref={canvasRef}
            className="fixed inset-0 w-full h-full pointer-events-none"
            style={{ zIndex: 0 }}
        />
    );
}

// apps/cloud-start-page/app/components/MatrixRain.vue
<script setup lang="ts">
import { createMatrixRain } from "matrix-rain";

const canvas = ref<HTMLCanvasElement | null>(null);
let controller: ReturnType<typeof createMatrixRain> | null = null;

onMounted(() => {
  controller = createMatrixRain(canvas.value!, { color: [255, 94, 31], headColor: [255, 240, 220] });
});

onUnmounted(() => {
  controller?.destroy();
  controller = null;
});
</script>

<template>
  <canvas ref="canvas" class="fixed inset-0 w-full h-full pointer-events-none" style="z-index: -1" />
</template>
